config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
get '/' => 'users#index'
post '/sessions' =>'sessions#create'
post '/users' => 'users#create'
get '/home' => 'guests#index'
delete '/sessions.current' => 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/guests_controller.rb
class GuestsController < ApplicationController
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

def create
	user = User.find_by(email:login_params[:email])
	if user && user.authenticate(login_params[:password])
		session[:user_id] = user.id
		redirect_to '/home'
	else
		flash.now.alert = "wrong password or email"
		redirect_to '/'
	end
end

def destroy
	session[:user_id] = nil
	redirect_to '/'
end




private 
	def login_params
		params.require(:login).permit(:email, :password)
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

def index

end 

def create
	user = User.new(user_params)
	if user.save
		session[:user_id] = user.id
		redirect_to "/home"
	else
		flash[:register_errors] =['invalid details']
		redirect_to'/' 
	end
end


private
 def user_params
	params.require(:user).permit(:fname, :lname, :email, :password, :password_confirmation)
 end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/guests_helper.rb
module GuestsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/guests/index.html.erb
<html lang="en">
<title>Dolphine.co.ke</title>
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
 <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
 <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  
  <style>
  .jumbotron{
      background-color: #0d47a1;
      color:#ffffff;
      padding-top:30px;
      padding-bottom:250px;
       }

      body{
        font:400  15px "Montserrat",sans-serif;
        line-height:2.0;

      }
      h1{
        font-size:24px;
        color:#000000;
        font-weight:600;
        margin-bottom:25px;
      }

      h4{
      font-size:18px;
        color:#fff;
        font-weight:400;
        margin-bottom:25px;
      }
      .row{
        margin-top: 20px;
      }
  .slideanim{visibility:hidden;}
  .slide{
    animation-name: slide;
    -webkit-animation-name: slide;
    animation-duration: 1s;
    -webkit-animation-duration:1s;
    visibility:visible;
  }
  @keyframes slide{
    0%{
      opacity:0;
      transform:translateY(70%);
    }
    100%{
      opacity:1;
      transform: translateY(0%);
    }
  }
  @-webkit-keyframes slide{
    0%{
      opacity: 0;
      -webkit-transform:translateY(70%);
    }
    100%{
      opacity: 1;
      -webkit-transform:translateY(0%);
    }
  }
  @media screen and (max-width: 768px){
    .col-sm-4{
      text-align: center;
      margin: 25px 0;
    }
  }

  </style>
</head>
<body>
<div class="jumbotron text-center">
  <div class="row col-md-offset-10">
   <%= link_to "Log Out", sessions_path("current"), method: "delete"%>
 </div>
    <%=image_tag("logo.jpeg", :style =>'height:150px;')%>
    <h1>Dolphine</h1>

    <h4>Enter the number and amount you would wish to send</h4>
  <form>
   <div class ="col-xs-6 col-md-offset-3">
     <div class="row">
       <label for="usr">Phone Number:</label>
       <input type="text" class="form-control" id="usr">
     </div>
     <div class="row">
       <label for="amount">Amount:</label>
       <input type="text" class="form-control" id="amount">
     </div>
     <div class="row">
      <button type="submit" class="btn btn-default" id="submitBtn" onClick="submitClick()">Submit</button>
     </div>
  </div>
 </form>
</div>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dolphine</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
   
  </head> 
  <body>
    <%= yield %>
  </body>
</html>

app/views/users/index.html.erb
<html lang="en">
<title>Dolphine.co.ke</title>
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
 <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
 <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <style>
  	 .jumbotron{
     background-color: #0d47a1;
      color:#ffffff;
      padding-top:200px;
      padding-bottom:200px;
       }

      body{
        font:400  15px "Montserrat",sans-serif;
        line-height:2.0;

      }
      h2{
        font-size:24px;
        color:#000000;
        font-weight:600;
        margin-bottom:25px;
      }

      h4{
      font-size:18px;
        color:#000000;
        font-weight:400;
        margin-bottom:25px;
      }
      h3{
        font-size:18px;
        color:#000000;
        font-weight:800;
        margin-bottom:25px;
      }
      button{
           margin:5px;
           padding:100px;
      }

.container-fluid{
  padding:30px 50px;
}
#myBtn{
  display:none;
  position:fixed;
  bottom:10px;
  right:20px;
  z-index:99;
  border:none;
  outline:none;
  background-color:#0d47a1;
  color:#fff;
  padding:15px;
  font-size:20px; 
  border-radius:10px;
}
 .navbar{
    margin-bottom:0;
    background-color: #0d47a1;
    z-index:9999;
    border:0;
    font-size:12px !important;
    letter-spacing: 4px;
    border-radius: 0;
  }
  .navbar li a, .navbar .navbar-brand {
      color: #fff !important;
  }
  .navbar-nav li a:hover, .navbar-nav li.active a {
      color: #0d47a1 !important;
      background-color: #fff !important;
  }
  .navbar-default .navbar-toggle {
      border-color: transparent;
      color: #fff !important;
  }
  .slideanim{visibility:hidden;}
  .slide{
    animation-name: slide;
    -webkit-animation-name: slide;
    animation-duration: 1s;
    -webkit-animation-duration:1s;
    visibility:visible;
  }
  @keyframes slide{
    0%{
      opacity:0;
      transform:translateY(70%);
    }
    100%{
      opacity:1;
      transform: translateY(0%);
    }
  }
  @-webkit-keyframes slide{
    0%{
      opacity: 0;
      -webkit-transform:translateY(70%);
    }
    100%{
      opacity: 1;
      -webkit-transform:translateY(0%);
    }
  }
  @media screen and (max-width: 768px){
    .col-sm-4{
      text-align: center;
      margin: 25px 0;
    }
  }
  </style>

</head>
<body id="login" data-spy="scroll" data-target=".navbar" data-offset="60">
	<nav class="navbar navbar-default navbar-fixed-top">
		<div class="container">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navBar">
					<span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
			</div>
			<div class="collapse navbar-collapse" id="Navbar">
				<ul class="nav navbar-nav navbar-right">
					<li><a href="#about">ABOUT</a></li>
					<li><a href="#contact">CONTACT</a></li>    
				</ul>
			</div>
		</div>
	</nav>
		

 <div class="jumbotron text-center">
  <%=image_tag("logo.jpeg")%>
	<h1>Dolphine</h1>
	<p>Send money in a flash!</p>

  <!--log in modal-->
	<button type="button" class="btn btn-default" data-toggle="modal" data-target="#login-modal">LOG IN</button>
  <div class="modal fade" id="login-modal" role="dialog">
  <div class="modal-dialog">
    <div class="loginmodal-container">
      <div class="modal-header">
         <button type="button" class="close" data-dismiss="modal">&times;</button>
         <h4 class="modal-title">Login to your account</h4>
          </div>
      <form action="/sessions" method="POST">
    <div class="form-group">
      <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">
      <label for="email">Email:</label>
      <input type="email" class="form-control" id="email" placeholder="Enter email" name="login[email]">
    </div>
    <div class="form-group">
      <label for="pwd">Password:</label>
      <input type="password" class="form-control" id="pwd" placeholder="Enter password" name="login[password]">
    </div>
    <div class="checkbox">
      <label><input type="checkbox" name="remember"> Remember me</label>
    </div>
    <button type="submit" class="btn btn-default">Submit</button>
  </form>
     
    </div>
  </div>
 </div>
 <!--sign up modal-->
	 <button type="button" class="btn btn-default" data-toggle="modal" data-target="#signup-modal">SIGN UP</button>
   <div class="modal fade" id="signup-modal" role="dialog">
  <div class="modal-dialog">
    <div class="loginmodal-container">
      <div class="modal-header">
         <button type="button" class="close" data-dismiss="modal">&times;</button>
         <h4 class="modal-title">New member</h4>
          </div>
      <form action="/users" method="POST">
        <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">
    <div class="form-group">
      <label for="fname">First Name:</label>
      <input type="text" class="form-control" id="fname" placeholder="Enter first names" name="user[fname]">
    </div>
    <div class="form-group">
      <label for="lname">Last Name:</label>
      <input type="text" class="form-control" id="lname" placeholder="Enter last name" name="user[lname]"> 
    </div>
     <div class="form-group">
      <label for="email">Email:</label>
      <input type="email" class="form-control" id="email" placeholder="Enter email" name="user[email]">
    </div>
    <div class="form-group">
      <label for="pwd">Password:</label>
      <input type="password" class="form-control" id="pwd" placeholder="Enter password" name="user[password]">
    </div>
     <div class="form-group">
      <label for="confirmpwd">Confirm Password:</label>
      <input type="password" class="form-control" id="confirmpwd" placeholder="Re-type password" name="user[password_confirmation]">
    </div>
    <div class="checkbox">
      <label><input type="checkbox" name="remember"> Remember me</label>
    </div>
    <button type="submit" class="btn btn-default">Submit</button>
  </form>
     
    </div>
  </div>
 </div>

 </div>

 <!--About-->
 <div id="about" class="container-fluid">
 	<div class="row">
 		<div class="col-sm-12">
 			<h2 class="text-center">OUR STORY</h2>
 			<p>Dolphin is an online money transaction platform that allows you to send monet to you family and friends in a blink of an eye.Simply enter the amount and phone number of user and that is it!<p/>
 				<p>We are the leading mobile money transfer platform in the Southern Sahara with three million users using our services on a daily basis.As a company we are on standby to listen to your needs anytime you need our assistance.</p>
 		</div>
 	</div>
 </div>

 <!--Contact section-->
 <div id="contact" class="container-fluid">
  <h2 class="text-center">CONTACT</h2>
  <div class="row">
    <div class="col-sm-4">
      <h3>Get in touch with us</h3>
      <p><span class="glyphicon glyphicon-map-marker"></span> Majengo,Mombasa Kenya</p>
      <p><span class="glyphicon glyphicon-phone"></span> +254 7532657</p>
      <p><span class="glyphicon glyphicon-envelope"></span> mwatelaraycee33@gmail.com</p>
    </div>
      <div class="col-sm-6 slideanim">
        <div class="row">
          <div class="col-sm-6 form-group">
           <form action="https://formspree.io/mwatelaraycee33@gmail.com"
      method="POST">
            <input class="form-control" id="name" name="name" placeholder="Name" type="text" required>
          </div>
           <div class="col-sm-6 form-group">
            <input class="form-control" id="email" name="_replyto" placeholder="Email" type="email" required>
          </div>
            <textarea class="form-control" id="comment" name="comment" placeholder="Comment" rows="5"></textarea><br>

            <input class="hidden" type="text" name="_gotcha" style="display:none">
            <input class="hidden" type="hidden" name="_subject" value="Message via http://domain.com">
            <div class="row">
                <button class="btn btn-default pull-right" type="submit">Send</button>
              </form>
            </div>
          </div>
        </div>
      </div>
 </div>

<button onclick="topFunction()" id="myBtn" title="Go to top">
	<span class="glyphicon glyphicon-menu-up"></span></button>

   <!--FOOTER-->
  <footer class="container-fluid text-center">
  <a href ="#login" title="To Top">
    <p>All rights reserved@2018|<strong>By Raycee</strong></p>
  </a>
</footer>
<script>
  $(document).ready(function(){
  $(".navbar a,footer a[href='#login']").on('click',function(event){
  if(this.has!==""){
  event.preventDefault();

  var hash = this.hash;

  $('html,body').animate({
  scrollTop: $(hash).offset().top
},900, function(){
  
  window.location.hash = hash;
 });
} //end if
});
$(window).scroll(function() {
    $(".slideanim").each(function(){
      var pos = $(this).offset().top;

      var winTop = $(window).scrollTop();
        if (pos < winTop + 600) {
          $(this).addClass("slide");
         }
      });
  });
})

  window.onscroll = function() {scrollFunction()};

function scrollFunction() {
    if (document.body.scrollTop > 20 || document.documentElement.scrollTop > 20) {
        document.getElementById("myBtn").style.display = "block";
    } else {
        document.getElementById("myBtn").style.display = "none";
    }
}
function topFunction() {
    document.body.scrollTop = 0;
    document.documentElement.scrollTop = 0;
}

</script>
</body>
</html>